<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Jewellery Designer Manual',
            'Diamond Jewellery Designer',
            'Gold Jewellery Designer',
            'Platinum Jewellery Designer',
            'E Commerce Jewellery Designer',
            'Export Market Jewellery Designer',
            'Couture Jewellery Designer',
            'Bridal Jewellery Designer',
            'Red Carpet Jewellery Designer',
            'Freelance Jewellery Designer Manual',
            'Jewellery Merchandiser',
            'Product Developer',
            'CAD Developer',
            'CAM',
            'Z Brush',
            'Rendering',
            'Corel Jewellery Designer',
            'Jewel Cad',
            '3D Printing',
            'ProCreate',
            '2D Artist / Model Maker',
            '3D Artist / Model Maker',
            'Mould Maker',
            'Quality Check',
            'Diamond Jewellery Manufacturer',
            'Diamond Jewellery Wholesaler',
            'Diamond Jewellery Retailer',
            'Gold Jewellery Manufacturer',
            'Gold Jewellery Wholesaler',
            'Gold Jewellery Retailer',
            'Silver Jewellery Manufacturer',
            'Silver Jewellery Wholesaler',
            'Silver Jewellery Retailer',
            'Platinum Jewellery Manufacturer',
            'Platinum Jewellery Wholesaler',
            'Platinum Jewellery Retailer',
            'Antique Jewellery Manufacturer',
            'Antique Jewellery Wholesaler',
            'Antique Jewellery Retailer',
            'Fashion Jewellery Manufacturer',
            'Fashion Jewellery Wholesaler',
            'Fashion Jewellery Retailer',
            'Diamond Mining',
            'Designer Jewellery',
            'Diamond Manufacturer',
            'Diamond Broker',
            'Diamond Retailer',
            'Diamond Grader',
            'Diamond Trader',
            'Diamond Assorter',
            'Gemstone Mining',
            'Gemstone Manufacturer',
            'Gemstone Wholesaler',
            'Gemstone Retailer',
            'Gemstone Grader',
            'Gemstone Trader',
            'Gemstone Assorter',
            'Lab Grown Diamond Manufacturer',
            'Lab Grown Diamond Wholesaler',
            'Lab Grown Diamond Retailer',
            'Lab Grown Gemstones Manufacturer',
            'Lab Grown Gemstones Wholesale',
            'Lab Grown Gemstones Retailer',
            'Swarovski Zirconia Manufacturer',
            'Swarovski Zirconia Wholesaler',
            'Swarovski Zirconia Retailer',
            'Swarovski Zirconia Jewellery',
            'Watch Manufacturer',
            'Watch Wholesaler',
            'Watch Retailer',
            'Watch Grader',
            'Watch Maker',
            'Fashion Jewellery',
            'Bullion Trading',
            'Artefacts',
            'Auction House',
            'Auctioneer',
            'Valuer',
            'Trader',
            'Business Coach',
            'Karigar / Craftsman',
            'Raw Materials',
            'Gems and Jewellery Trade Association',
            'Silver Trade Association',
            'Trade Association',
            'Jewellery Awards',
            'Gems and Jewellery Trade Exhibition / Show',
            'Lifestyle Exhibition',
            'Luxury Exhibition',
            'Publication Magazine',
            'Newspaper Publication',
            'Digital Publication',
            'Public Relations Agency (PR)',
            'Public Relations Freelancer (PR)',
            'Digital Marketing Agency',
            'Digital Marketing Freelancer',
            'Social Media Marketing Agency',
            'Social Media Marketing Freelancer',
            'Marketing Agency',
            'Branding Agency',
            'Branding Freelancer',
            'Advertising Agency',
            'Graphic Designer',
            'Logo Designer',
            'Mobile Marketing',
            'Billboard / Hoarding Marketing',
            'ATL Marketing',
            'BTL Marketing',
            'Radio Marketing',
            'TV Marketing',
            'Website Developer',
            'Mobile App Developer',
            'Software Developer',
            'SEO Expert',
            'Email Marketing',
            'Whats App Marketing',
            'SMS Marketing',
            'Linkedin Marketer',
            'Facebook Marketer',
            'Instagram Marketer',
            'Influencer Marketer',
            'Youtube Marketer',
            'Performance Marketing',
            'Market Research Analyst',
            'UX UI Designer',
            'AI Developer',
            'AI Expert',
            'Ecommerce',
            'Payment Gateways',
            'Wikipedia Specialist',
            'Blue Tick Verification',
            '3D Animator',
            'Book Store',
            'Consultant',
            'Customer Relation Manager',
            'Security Solutions',
            'Ethical Hacking',
            'Illustrator',
            'Adobe Premiere Pro',
            'Social Media Influencer / Blogger',
            'Jewellery Influencer / Blogger',
            'Lifestyle Influencer',
            'Luxury Influencer',
            'Journalist',
            'Script Writer',
            'Content Writer',
            'Trademark and Registration',
            'Copywriter',
            'Fashion Stylist',
            'Jewellery Stylist',
            'Makeup and Hair Artist',
            'Event Manager',
            'Wedding Planner',
            'Product Photographer',
            'Fashion Photographer',
            'Advertising Photographer',
            'Documentary',
            'Digital Photographer',
            'Event Photographer',
            'Mobile Photographer',
            'Photography Studio',
            'Photography Agency',
            'Video Editor',
            'Models',
            'Choreographer',
            'Packaging',
            'Display',
            'Visual Merchandiser',
            'Fabricator',
            'Store Lighting',
            'Store Interiors',
            'HR / Recruitment Agency',
            'Logistics',
            'Angadia',
            'Courier',
            'Insurance',
            'Chartered Accountant',
            'Auditor',
            'Financial Advisor',
            'Banking Partner',
            'Investor',
            'Education Institute',
            'Laboratory',
            'Gems and Jewellery Instructor',
            'Hallmarking',
            'Enamelling',
            'Laser Engraving',
            'Ear Piercings',
            'Piercings',
            'Gems and Jewellery Tools',
            'Gems and Jewellery Equipments',
            'Cleaning Solutions',
            'Jewellery Cleaning',
            'Stationery',
            'Gifting Items',
            'Awards / Trophy Manufacturer',
            'Machinery',
            'Technology',
            'NGO',
            'Travel Agent',
            'Co Working Space',
            'Apps',
            'Others'
        ];

        foreach ($categories as $name) {
            Category::firstOrCreate(['name' => $name]);
        }
    }
}
